apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-client
  ports:
    - port: 80
      targetPort: {{ .Values.client.port }}
